### ISSUE TITLE
On OSX 10.14, the text is hardly visible (see screenshot)

### ISSUE THREAD

**Issue by rggjan** [macmade/ccache-gui#1]
<img width="360" alt="image" src="https://user-images.githubusercontent.com/128554/46144763-36636c80-c25e-11e8-812e-43b444580ac8.png">

**Comment by rggjan** [comment]
Why was this closed?

**Comment by macmade** [comment]
This has been fixed in 0.1.10.

**Comment by rggjan** [comment]
It has, thanks! Was confused about the `wontfix` label :)
